image_root: ''
ann_root: 'annotation'
dataset: 'coco'

# set pretrained as a file path or an url
# pre-trained on 129M dataimages
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_coco.pth'

vit: 'base'
batch_size_train: 32
batch_size_test: 256
vit_grad_ckpt: True
vit_ckpt_layer: 4
init_lr: 1e-5

image_size: 384
queue_size: 57600
alpha: 0.4
k_test: 256
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 6