image_root: '' # set the path to your image root directory
ann_root: 'annotation'
dataset: '' # set the dataset name, e.g., 'coco' or 'flickr'

# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large.pth'

vit: 'large'
batch_size_train: 32
batch_size_test: 64
vit_grad_ckpt: True
vit_ckpt_layer: 12
init_lr: 5e-6

image_size: 384
queue_size: 57600
alpha: 0.4
k_test: 128
negative_all_rank: False

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 6

